## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [2]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [3]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [11]:
y1=y[:40]
x1=X[:40]
y2=y[40:]
x2=X[40:]
print(y1.shape)
print(y2.shape)

(40,)
(160,)


In [12]:
from sklearn.model_selection import train_test_split, KFold
x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1,test_size=0.25)
x2_train, x2_test, y2_train, y2_test = train_test_split(x2,y2,test_size=1/16)

In [30]:
print(x1_train.shape)
print(x2_train.shape)

(30, 5)
(150, 5)


In [31]:
import pandas as pd
x_train = np.concatenate((x1_train,x2_train),axis=0)
y_train = np.concatenate((y1_train,y2_train),axis=0)
x_test = np.concatenate((x1_test,x2_test),axis=0)
y_test = np.concatenate((y1_test,y2_test),axis=0)

In [33]:
print(x_test)
print(y_test)

[[ 35  36  37  38  39]
 [ 50  51  52  53  54]
 [ 40  41  42  43  44]
 [100 101 102 103 104]
 [180 181 182 183 184]
 [ 15  16  17  18  19]
 [ 65  66  67  68  69]
 [ 10  11  12  13  14]
 [ 25  26  27  28  29]
 [185 186 187 188 189]
 [895 896 897 898 899]
 [650 651 652 653 654]
 [405 406 407 408 409]
 [995 996 997 998 999]
 [205 206 207 208 209]
 [890 891 892 893 894]
 [245 246 247 248 249]
 [570 571 572 573 574]
 [525 526 527 528 529]
 [585 586 587 588 589]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
